### Gets all the hotels
GET http://localhost:8080/hotels/all
Content-Type: application/json

### Gets hotel by name
GET http://localhost:8080/hotels/Ibis
Content-Type: application/json

### POST request to checkin some guests
POST http://localhost:8080/hotels/checkIn
Content-Type: application/json

{
    "hotelName": "Ibis",
    "nbrGuests": 4
}

###